spring:
  profiles:
    active:
    - heroku
    - jwt
  datasource:
    hikari.maximum-pool-size: 4
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT 설정 값
jwt:
  secret-key: ${jwt.secret-key}
  token:
    expired-time-ms: ${jwt.token.expired-time-ms}